=== Senseering/se-mde-workerjs/src/utils/config/schema/config.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "credentials",
        "url",
        "settings",
        "profile",
        "privKey",
        "schema",
        "info",
        "payment",
        "meta"
    ],
    "properties": {
        "credentials": {
            "$id": "#/properties/credentials",
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}:[0-9a-f]{32}$",
            "examples": [
                "5e0b2680-8484-11ea-bd6c-2b4b0702ce34:8872bad4ed484763bbee806aac62ff1a"
            ]
        },
        "url": {
            "$id": "#/properties/url",
            "type": "string",
            "format": "uri-reference",
            "examples": [
                "http://35.157.82.188"
            ]
        },
        "settings": {
            "$id": "#/properties/settings",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "qualityOfService"
            ],
            "properties": {
                "qualityOfService": {
                    "$id": "#/properties/profile/properties/settings/properties/qualityOfService",
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 1
                },
                "messageRetries": {
                    "$id": "#/properties/profile/properties/settings/properties/messageRetries",
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 100
                },
                "messageTimeout": {
                    "$id": "#/properties/profile/properties/settings/properties/messageTimeout",
                    "minimum": 100
                }
            }
        },
        "payment": {
            "$id": "#/properties/profile/properties/payment",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "fixCost",
                "isFixCostOnly"
            ],
            "properties": {
                "fixCost": {
                    "$id": "#/properties/profile/properties/payment/properties/fixCost",
                    "type": "integer"
                },
                "isFixCostOnly": {
                    "$id": "#/properties/profile/properties/payment/properties/isFixCostOnly",
                    "type": "boolean"
                }
            }
        },
        "profile": {
            "$id": "#/properties/profile",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "name",
                "location"
            ],
            "properties": {
                "name": {
                    "$id": "#/properties/profile/properties/name",
                    "type": "string",
                    "minLength": 5,
                    "maxLength": 32
                },
                "location": {
                    "$id": "#/properties/profile/properties/location",
                    "type": "object",
                    "additionalProperties": false,
                    "required": [
                        "latitude",
                        "longitude"
                    ],
                    "properties": {
                        "latitude": {
                            "$id": "#/properties/profile/properties/location/properties/latitude",
                            "type": "number"
                        },
                        "longitude": {
                            "$id": "#/properties/profile/properties/location/properties/longitude",
                            "type": "number"
                        }
                    }
                }
            }
        },
        "privKey": {
            "$id": "#/properties/privKey",
            "type": "string",
            "anyOf": [
                {
                    "format": "uri-reference"
                },
                {
                    "regexp": { "pattern": "^-{5}.{21}-{5}.*-{5}.{19}-{5}$", "flags": "gms" }
                }
            ],
            "examples": [
                "./env/key.pem"
            ]
        },
        "schema": {
            "$id": "#/properties/schema",
            "type": "object",
            "additionalProperties": {
                "community": {
                    "$id": "#/properties/schema/properties/community",
                    "type": "string",
                    "format": "uri-reference",
                    "examples": [
                        "https://github.com/Senseering/worker_js/tree/bf3c27c50ece0ed9830e272e485112b4c8558ead"
                    ]
                }
            },
            "required": [
                "input",
                "output"
            ],
            "properties": {
                "input": {
                    "$id": "#/properties/schema/properties/input",
                    "oneOf": [
                        {"type": "string"},
                        {"type": "object"}
                    ],
                    "examples": [
                        "./env/schema/input.json",
                        "json schema"
                    ]
                },
                "output": {
                    "$id": "#/properties/schema/properties/output",
                    "oneOf": [
                        {"type": "string"},
                        {"type": "object"}
                    ],
                    "examples": [
                        "./env/schema/output.json",
                        "json schema"
                    ]
                }
            }
        },
        "info": {
            "$id": "#/properties/info",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "worker",
                "input",
                "output"
            ],
            "properties": {
                "worker": {
                    "$id": "#/properties/info/properties/worker",
                    "type": "object",
                    "additionalProperties": false,
                    "required": [
                        "description",
                        "tags"
                    ],
                    "properties": {
                        "description": {
                            "$id": "#/properties/info/properties/worker/properties/description",
                            "type": "string",
                            "examples": [
                                "./env/description/worker.md",
                                "markdown"
                            ]
                        },
                        "tags": {
                            "$id": "#/properties/info/properties/worker/properties/tags",
                            "type": "array",
                            "additionalItems": true,
                            "items": {
                                "$id": "#/properties/info/properties/worker/properties/tags/items",
                                "type": "string"
                            }
                        }
                    }
                },
                "input": {
                    "$id": "#/properties/info/properties/input",
                    "type": "object",
                    "additionalProperties": false,
                    "required": [
                        "description",
                        "tags"
                    ],
                    "properties": {
                        "description": {
                            "$id": "#/properties/info/properties/input/properties/description",
                            "type": "string",
                            "examples": [
                                "./env/description/input.md",
                                "markdown"
                            ]
                        },
                        "tags": {
                            "$id": "#/properties/info/properties/input/properties/tags",
                            "type": "array",
                            "additionalItems": true,
                            "items": {
                                "$id": "#/properties/info/properties/input/properties/tags/items",
                                "type": "string"
                            }
                        }
                    }
                },
                "output": {
                    "$id": "#/properties/info/properties/output",
                    "type": "object",
                    "additionalProperties": false,
                    "required": [
                        "description",
                        "tags"
                    ],
                    "properties": {
                        "description": {
                            "$id": "#/properties/info/properties/output/properties/description",
                            "type": "string",
                            "examples": [
                                "./env/description/output.md",
                                "markdown"
                            ]
                        },
                        "tags": {
                            "$id": "#/properties/info/properties/output/properties/tags",
                            "type": "array",
                            "additionalItems": true,
                            "items": {
                                "$id": "#/properties/info/properties/output/properties/tags/items",
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "meta": {
            "$id": "#/properties/meta",
            "type": "object",
            "additionalProperties": true
        }
    }
}

=== Senseering/se-mde-workerjs/test/data/badURLConfig.json
{
  "credentials": "5e0b2680-8484-11ea-bd6c-2b4b0702ce34:8872bad4ed484763bbee806aac62ff1a",
  "url": "35.157.82.188",
  "settings": {
    "qualityOfService": 1,
    "messageRetries": 3,
    "messageTimeout": 1000
  },
  "meta": {},
  "payment": {
    "fixCost": 0,
    "isFixCostOnly": false
  },
  "profile": {
    "name": "Example Source",
    "location": {
      "latitude": 52.5297268,
      "longitude": 13.400391
    }
  },
  "privKey": "./test/data/env/key.pem",
  "schema": {
    "input": "./test/data/env/schema/input.json",
    "output": "./test/data/env/schema/output.json"
  },
  "info": {
    "worker": {
      "description": "./test/data/env/description/worker.md",
      "tags": [
        "image processing"
      ]
    },
    "input": {
      "description": "./test/data/env/description/input.md",
      "tags": [
        "h"
      ]
    },
    "output": {
      "description": "./test/data/env/description/output.md",
      "tags": [
        ""
      ]
    }
  }
}
